### PR TITLE
xencrypt-ed powershell payload still trigger the AMSI

### PR DESCRIPTION
**Pull request by GetRektBoy724**
i generate payload from msfvenom....and using xencrypt to encrypt it but the amsi still getting triggered
it says that the amsi get triggered by "FromBase64String"
pls fix it :D

### CODE REVIEW

**Comment by GetRektBoy724** [comment]
i will later scan the xencrypt-ed powershell payload with amsitrigger

**Review by S3cur3Th1sSh1t — COMMENTED** [review]
.

**Comment by GetRektBoy724** [comment]
is it fixed already?

**Comment by the-xentropy** [comment]
Is this just a pull request to merge current dev into master?

Dev is very broken and features a bunch of stuff I never got around to implementing.

**Comment by BurntDog** [comment]
> is it fixed already?

Don't be a script kiddie, I made this GPLv3 so you can make your own modifications. This tool is intended as a demo for how easy it is to write your own crypter. It works for its intended purpose and I will not patch it to make it suitable for yours.

**Comment by GetRektBoy724** [comment]
decided to create my own modification with Xencrypt,now its completely FUD again
https://github.com/GetRektBoy724/BetterXencrypt

**Pull request closed without merging**
